name: CI

on:
  push

env:
  GITHUB_ACTIONS: RUNNING

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install -y llvm
        rustup toolchain install nightly
        rustup component add clippy --toolchain nightly
        cargo install rustfilt

    - name: Run `ci.sh`
      run: sh ci.sh
